### ISSUE TITLE
We need to add driver specs for SFC with Opflex agent hosts

### ISSUE THREAD

**Issue by skandasw** [noironetworks/tripleo-ciscoaci#21]
In running some tests on Ifti's 142 FAB (supporting SVI and SFC workflows with Opflex Agent) - found that AIM driver was not getting instantiated on SFC workflows. 

In /var/lib/config-data/puppet-generated/neutron/etc/neutron/plugins/ml2/ml2_conf_cisco_apic.ini  

we are missing:

[sfc]
drivers = aim

[flowclassifier]
drivers = aim

Clarified with Ifti and with this update locally things are better.

**Comment by tbachman** [comment]
This was resolved with:
stable/queens:
https://github.com/noironetworks/ciscoaci-puppet/commit/48de7f72047c382b37eebb818ec7474b01d39a6f
stable/train:
https://github.com/noironetworks/ciscoaci-puppet/commit/48de7f72047c382b37eebb818ec7474b01d39a6f
