### ISSUE TITLE
lldp healthceck command broken

### ISSUE THREAD

**Issue by timeu** [noironetworks/tripleo-ciscoaci#81]
The lldp healthcheck script was rendered using the wrong template: https://github.com/noironetworks/ciscoaci-puppet/blob/train/ciscoaci-puppet/ciscoaci/manifests/lldp.pp#L18

**Comment by tbachman** [comment]
Thanks for catching this! This was closed in stable/train with the PR you posted:
https://github.com/noironetworks/ciscoaci-puppet/pull/51

A similar fix has also been made to stable/queens:
https://github.com/noironetworks/ciscoaci-puppet/pull/58

Thanks for the fix! We'll close this once the queens patch merges.

**Comment by tbachman** [comment]
The queens patch was merged - closing.
